# To do:
# 1. Build instance name 
# 2. Apply instance name to Elastic beanstalk
# 3. Apply instance name to RDS
# 4. Apply instance name to Redis
# 5. Set up VPC

AWSTemplateFormatVersion: 2010-09-09

Description: Travis user  for multi-docker environment

Parameters:
  # Environment
  UserNameParameter: 
    Type: String
    Description: User name
  
Resources:
  # User name
  UserNameResource:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref UserNameParameter
      ManagedPolicyArns:
        #- arn:aws:iam::aws:policy/AWSElasticBeanstalkCustomPlatformforEC2Role
        #- arn:aws:iam::aws:policy/service-role/AWSElasticBeanstalkEnhancedHealth
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkFullAccess
        #- arn:aws:iam::aws:policy/AWSElasticBeanstalkMulticontainerDocker
        #- arn:aws:iam::aws:policy/AWSElasticBeanstalkReadOnlyAccess
        #- arn:aws:iam::aws:policy/service-role/AWSElasticBeanstalkService
        #- arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier
        #- arn:aws:iam::aws:policy/AWSElasticBeanstalkWorkerTier
  UserNameAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref UserNameResource
      Status: Active

    

